on:
  push:
    branches:
      - main
  pull_request:

name: Continuous Integration

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Tauri dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Setup Node
        uses: josh-development/.github/setup-node@main

      - name: Build
        run: yarn tauri build
